import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Acceloka",
  description: "Generated by create next app",
};

import Footer from "@/components/Footer";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen font-sans antialiased bg-gray-50">
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
